accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path("login/", auth_views.LoginView.as_view(template_name="accounts/login.html"),name='login'),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", views.SignUp.as_view(), name="signup"),
]

posts/urls.py
from django.urls import path

from . import views

app_name='posts'

urlpatterns = [
    path("", views.PostList.as_view(), name="all"),
    path("new/", views.CreatePost.as_view(), name="create"),
    path("by/<username>/",views.UserPosts.as_view(),name="for_user"),
    path("by/<username>/<pk>/",views.PostDetail.as_view(),name="single"),
    path("delete/<pk>/",views.DeletePost.as_view(),name="delete"),
]

safespace/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(), name="home"),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("test/", views.TestPage.as_view(), name="test"),
    path("thanks/", views.ThanksPage.as_view(), name="thanks"),
    path("posts/", include("posts.urls", namespace="posts")),
    path("groups/",include("groups.urls", namespace="groups")),
    path("about/", views.AboutPage.as_view(), name="about")
]

templates/about.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
<link rel="stylesheet" href="/css/master.css">


<h1 class="intro">LIFE IS TOO SHORT FOR BEING JUDGED.</h1>


<div class="">
<h1 class="fet h1">✨A Place Where You Can Be Yourself.</h1>
<br>
<div class="about">

<h3>In this era where everything is judged we here provide you a place to be real and yourself! We aim to provide a platform to people who are unable to share their thoughts in the open and have a lot to say. we assure you a 100% judgement free zone.
<br><br>
Along with expressing yourself you can approach us if you need any kind of help, be it financial, emotional or educational. Just reach out to us and we'll see what we can do.
<br><br>
This is also a place where we connect the youth to contribute to the social cause. We are more than welcome to include volunteers in our team. Check out the form if you are interested.

</h3>
</div>

</div>
<br>
<br>
<section id="testimonials">
  <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <h2>💜You can now share your views openly with everyone.💜</h2>
      </div>
      <div class="carousel-item">
        <h2>🤝🏻You can reach out to us for any kind of help!🤝🏻</h2>
      </div>
      <div class="carousel-item">
        <h2>🙌🏻You can also contribute by joining our team and volunteering with us!🙌🏻</h2>
      </div>
    </div>

  </div>
</section>
<br>
<section id="cta">

    <h3 class"cta-desc">If you are interested in volunteering click below.</h3>
    <a href="https://docs.google.com/forms/d/e/1FAIpQLSc7-sCS9qUB7mS-s_YWGYoxz5aeHJOhAHC_GhApa6oSCXLt5Q/viewform?usp=sf_link">Volunteer Now!</a>


  </section>

<footer id="footer">

    <p class="foot">© Copyright 2020 SafeSpace</p>

  </footer>

{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>SafeSpace</title>

    <!-- Latest compiled and minified CSS -->

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Rubik&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/master.css'%}">


  </head>


  <body>

    <nav class="navbar  mynav" role="navigation" id="navbar">
    			<div class="container">

            <a class="navbar-brand mynav" href="{% url 'home' %}">Safespace</a>

    					<ul class="nav navbar-nav navbar-right">
    						{% if user.is_authenticated %}
                      <li><a href="{% url 'posts:create' %}" class="btn btn-simple">Post</a></li>
                      <li><a href="{% url 'groups:all' %}" class="btn btn-simple">Groups</a></li>
                      <li><a href="{% url 'groups:create' %}" class="btn btn-simple">Create Group</a></li>
                      <li><a href="{% url 'accounts:logout' %}" class="btn btn-simple">Log out</a></li>
                      <li><a href="{% url 'about'%}" class="btn btn-simple">About Us</a></li>
    						{% else %}
    						      <li><a href="{% url 'groups:all' %}"class="btn btn-simple">Groups</a></li>
    						      <li><a href="{% url 'accounts:login' %}" class="btn btn-simple">Log in</a></li>
    						      <li><a href="{% url 'accounts:signup' %}" class="btn btn-simple">Sign up</a></li>
                      <li><a href="{% url 'about'%}" class="btn btn-simple">About Us</a></li>
    						{% endif %}
    					</ul>



    			</div>
    		</nav>
        <div class="container mycontent">

          {% block content %}

          {% endblock %}

        </div>



<canvas id="canvas"></canvas>



  </body>
  <script src="{% static "safespace/js/master.js"%}" type="text/javascript" ></script>
</html>

templates/index.html
{% extends "base.html" %}
{% block content %}
    <br>
    <br>
    <h1 style="text-align:center; font-size:70px; color:#6be9ff;">🎆Welcome to SafeSpace🧧</h1>
    <h2 style="text-align:center; color:grey; font-size:20px;">We are here to help you!! We look forward to help you through this.</h2><br><br>
    <h2 style="text-align:center; font-size:40px; color:yellow;">You have entered a Non Judgmental Zone</h2>


{% endblock %}

templates/test.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <h1>🎇You are now logged in!🎇</h1>
  <h2><a href="{% url 'groups:all'%}">Go to Groups</a></h2>


</div>




{% endblock %}

templates/thanks.html
{% extends "base.html" %}
{% block content %}
<h1 style="text-align:center; font-size:50px;">Thanks for visiting! Come back soon!🤩😉</h1>

{% endblock %}